apiVersion: v1
kind: Service
metadata:
  name: board-service
spec:
  ports:
  - name: http
    port: 9090
    targetPort: 9090
  - name: mqtt
    port: 1883
    targetPort: 1883
  # just like the selector in the deployment,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    app: board
  type: LoadBalancer
